version: '3.8'

services:

  postgres:
    image: postgres
    container_name: nana-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nana
    volumes:
      - nana_pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
      DATABASE_URL: postgres://root:${POSTGRES_PASSWORD}@postgres:5432/nana
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    command: npm run start

volumes:
  nana_pg_data:
